export default function LeadersApplyPage() {
  const responsibilities = [
    "Welcome new members and facilitate orientation",
    "Run monthly workshops and skill-shares",
    "Steward a zone of the property (gardens, forest, structures)",
    "Help resolve disputes and maintain community harmony"
  ];

  const qualities = [
    "Good communicator and active listener",
    "Reliable and follows through on commitments",
    "Committed to permaculture ethics: Earth Care, People Care, Fair Share",
    "Team player who values collaboration over ego"
  ];

  const compensation = [
    {
      title: "Land Credit",
      description: "Earn equity toward your own lot on the property",
      icon: "🏡"
    },
    {
      title: "Reduced Membership",
      description: "50% off monthly membership dues",
      icon: "💰"
    },
    {
      title: "Profit Share",
      description: "5% of revenue generated by your stewarded zone",
      icon: "📈"
    }
  ];

  return (
    <main className="min-h-screen bg-cream">
      {/* Hero */}
      <section className="bg-forest text-cream py-20">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <h1 className="font-serif text-5xl mb-4">Lead the Land. Shape the Community.</h1>
          <p className="text-xl opacity-90">Become a community steward and earn while you serve</p>
        </div>
      </section>

      {/* What Leaders Do */}
      <section className="max-w-4xl mx-auto px-6 py-16">
        <h2 className="font-serif text-4xl text-forest mb-6">What Community Leaders Do</h2>
        <div className="bg-white border-2 border-forest rounded-lg p-8">
          <ul className="space-y-3">
            {responsibilities.map((item, idx) => (
              <li key={idx} className="flex items-start">
                <span className="text-gold text-xl mr-3">✓</span>
                <span className="text-gray-700 text-lg">{item}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* Qualities We Look For */}
      <section className="max-w-4xl mx-auto px-6 py-16">
        <h2 className="font-serif text-4xl text-forest mb-6">Qualities We Look For</h2>
        <div className="grid md:grid-cols-2 gap-4">
          {qualities.map((quality, idx) => (
            <div key={idx} className="bg-bark text-white p-6 rounded-lg">
              <p className="text-lg">{quality}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Time Commitment */}
      <section className="max-w-4xl mx-auto px-6 py-16">
        <div className="bg-gold text-white p-8 rounded-lg text-center">
          <h2 className="font-serif text-3xl mb-3">Time Commitment</h2>
          <p className="text-2xl font-bold">6-10 hours per week</p>
          <p className="mt-2 opacity-90">Flexible scheduling around your life</p>
        </div>
      </section>

      {/* Compensation */}
      <section className="max-w-6xl mx-auto px-6 py-16">
        <h2 className="font-serif text-4xl text-forest mb-8 text-center">How You're Compensated</h2>
        <div className="grid md:grid-cols-3 gap-6">
          {compensation.map((item, idx) => (
            <div key={idx} className="bg-white border-2 border-forest rounded-lg p-8 text-center">
              <div className="text-5xl mb-4">{item.icon}</div>
              <h3 className="font-serif text-2xl text-forest mb-3">{item.title}</h3>
              <p className="text-gray-700">{item.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Application Form */}
      <section className="max-w-4xl mx-auto px-6 py-16">
        <h2 className="font-serif text-4xl text-forest mb-8 text-center">Apply to Lead</h2>
        <form className="bg-white border-2 border-forest rounded-lg p-8 space-y-6">
          <div>
            <label className="block text-forest font-semibold mb-2">Full Name</label>
            <input type="text" className="w-full border-2 border-gray-300 rounded-lg px-4 py-3" />
          </div>
          <div>
            <label className="block text-forest font-semibold mb-2">Email</label>
            <input type="email" className="w-full border-2 border-gray-300 rounded-lg px-4 py-3" />
          </div>
          <div>
            <label className="block text-forest font-semibold mb-2">Current Location</label>
            <input type="text" className="w-full border-2 border-gray-300 rounded-lg px-4 py-3" />
          </div>
          <div>
            <label className="block text-forest font-semibold mb-2">Your Skills & Experience</label>
            <textarea rows={4} className="w-full border-2 border-gray-300 rounded-lg px-4 py-3"></textarea>
          </div>
          <div>
            <label className="block text-forest font-semibold mb-2">Why do you want to lead?</label>
            <textarea rows={4} className="w-full border-2 border-gray-300 rounded-lg px-4 py-3"></textarea>
          </div>
          <div>
            <label className="block text-forest font-semibold mb-2">Hours Available Per Week</label>
            <input type="number" className="w-full border-2 border-gray-300 rounded-lg px-4 py-3" />
          </div>
          <a
            href="/contact"
            className="block w-full bg-gold text-white text-center py-4 rounded-lg font-bold text-lg hover:bg-opacity-90 transition-colors"
          >
            Submit Application
          </a>
        </form>
      </section>
    </main>
  );
}
