export default function LeadersApplyPage() {
  const responsibilities = [
    { title: "Welcome New Members", desc: "Be the first friendly face and guide for newcomers" },
    { title: "Run Monthly Workshops", desc: "Lead educational sessions on your area of expertise" },
    { title: "Steward a Property Zone", desc: "Oversee maintenance and development of a specific area" },
    { title: "Help Resolve Disputes", desc: "Mediate conflicts with wisdom and fairness" }
  ];

  const qualities = [
    "Good communicator who listens and explains clearly",
    "Reliable and follows through on commitments",
    "Committed to permaculture ethics: Earth Care, People Care, Fair Share",
    "Team player who values collaboration over ego"
  ];

  const compensation = [
    {
      title: "Land Credit",
      icon: "🏞️",
      desc: "Earn equity toward a lot purchase. Every 10 hours = $100 credit."
    },
    {
      title: "Reduced Membership",
      icon: "🎫",
      desc: "50% discount on monthly membership dues while serving."
    },
    {
      title: "Profit Share",
      icon: "💰",
      desc: "Earn 5% of revenue generated by your zone or activities."
    }
  ];

  return (
    <div className="min-h-screen bg-cream">
      {/* Hero Section */}
      <section className="bg-forest text-cream py-20">
        <div className="container mx-auto px-6 text-center">
          <h1 className="font-serif text-5xl md:text-6xl mb-6">
            Lead the Land. Shape the Community.
          </h1>
          <p className="text-xl max-w-3xl mx-auto opacity-90">
            Become a community leader and help build something that lasts.
          </p>
        </div>
      </section>

      {/* What Leaders Do */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-6">
          <h2 className="font-serif text-4xl text-forest text-center mb-12">
            What Community Leaders Do
          </h2>
          <div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto">
            {responsibilities.map((item, idx) => (
              <div key={idx} className="border-2 border-forest rounded-lg p-6">
                <h3 className="font-serif text-2xl text-forest mb-3">{item.title}</h3>
                <p className="text-bark">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Qualities We Look For */}
      <section className="py-16">
        <div className="container mx-auto px-6">
          <h2 className="font-serif text-4xl text-forest text-center mb-12">
            Qualities We Look For
          </h2>
          <div className="max-w-3xl mx-auto bg-white border-2 border-forest rounded-lg p-8">
            <ul className="space-y-4">
              {qualities.map((quality, idx) => (
                <li key={idx} className="flex items-start text-bark">
                  <span className="text-gold text-2xl mr-4 flex-shrink-0">✓</span>
                  <span className="text-lg">{quality}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* Time Commitment */}
      <section className="py-16 bg-gold bg-opacity-10">
        <div className="container mx-auto px-6 text-center">
          <h2 className="font-serif text-4xl text-forest mb-6">Time Commitment</h2>
          <div className="max-w-2xl mx-auto">
            <div className="bg-white border-2 border-forest rounded-lg p-8">
              <div className="text-6xl font-bold text-forest mb-4">6-10 hrs/week</div>
              <p className="text-bark text-lg">
                Flexible schedule. Can be weekends, evenings, or daytime depending on your zone and role.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Compensation */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-6">
          <h2 className="font-serif text-4xl text-forest text-center mb-12">
            How Leaders Are Compensated
          </h2>
          <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {compensation.map((item, idx) => (
              <div key={idx} className="border-2 border-forest rounded-lg p-8 text-center hover:shadow-xl transition-shadow">
                <div className="text-6xl mb-4">{item.icon}</div>
                <h3 className="font-serif text-2xl text-forest mb-4">{item.title}</h3>
                <p className="text-bark">{item.desc}</p>
              </div>
            ))}
          </div>
          <p className="text-center text-bark mt-12 max-w-3xl mx-auto">
            Leaders can choose one compensation model or combine them. 
            We believe in rewarding those who invest their time and energy.
          </p>
        </div>
      </section>

      {/* Application Form */}
      <section className="py-16 bg-cream">
        <div className="container mx-auto px-6">
          <h2 className="font-serif text-4xl text-forest text-center mb-12">Apply to Lead</h2>
          <form className="max-w-3xl mx-auto bg-white border-2 border-forest rounded-lg p-8">
            <div className="space-y-6">
              <div>
                <label className="block text-forest font-semibold mb-2">Full Name *</label>
                <input
                  type="text"
                  className="w-full border-2 border-forest rounded px-4 py-3"
                  placeholder="Your name"
                  required
                />
              </div>
              
              <div>
                <label className="block text-forest font-semibold mb-2">Email Address *</label>
                <input
                  type="email"
                  className="w-full border-2 border-forest rounded px-4 py-3"
                  placeholder="your.email@example.com"
                  required
                />
              </div>
              
              <div>
                <label className="block text-forest font-semibold mb-2">Current Location *</label>
                <input
                  type="text"
                  className="w-full border-2 border-forest rounded px-4 py-3"
                  placeholder="City, State"
                  required
                />
              </div>
              
              <div>
                <label className="block text-forest font-semibold mb-2">Your Skills & Experience *</label>
                <textarea
                  className="w-full border-2 border-forest rounded px-4 py-3 h-32"
                  placeholder="Tell us about your relevant skills, experience, and what you'd bring to the role..."
                  required
                ></textarea>
              </div>
              
              <div>
                <label className="block text-forest font-semibold mb-2">Why Do You Want to Lead? *</label>
                <textarea
                  className="w-full border-2 border-forest rounded px-4 py-3 h-32"
                  placeholder="What motivates you to become a community leader at Uni-Phi?"
                  required
                ></textarea>
              </div>
              
              <div>
                <label className="block text-forest font-semibold mb-2">Hours Available Per Week *</label>
                <input
                  type="number"
                  className="w-full border-2 border-forest rounded px-4 py-3"
                  placeholder="6-10"
                  min="6"
                  required
                />
              </div>
            </div>

            <div className="mt-8 text-center">
              <a
                href="/contact"
                className="inline-block bg-forest text-cream px-12 py-4 rounded font-semibold text-lg hover:bg-opacity-90 transition"
              >
                Submit Application
              </a>
            </div>
          </form>
        </div>
      </section>
    </div>
  );
}
