import type { RoomModule, SnapConnector } from '@uniphimedia/shared-types';

const baseConnectors = (prefix: string): SnapConnector[] => [
  {
    id: `${prefix}_north_door`,
    face: 'north',
    position: 0.5,
    type: 'door',
    openingWidth: 0.9,
    openingHeight: 2.1,
    systems: ['electrical-120v', 'hvac-supply'],
    required: false,
  },
  {
    id: `${prefix}_south_wall`,
    face: 'south',
    position: 0.5,
    type: 'wall',
    systems: ['electrical-120v'],
    required: false,
  },
  {
    id: `${prefix}_east_wall`,
    face: 'east',
    position: 0.5,
    type: 'wall',
    systems: ['electrical-120v'],
    required: false,
  },
  {
    id: `${prefix}_west_wall`,
    face: 'west',
    position: 0.5,
    type: 'wall',
    systems: ['electrical-120v'],
    required: false,
  },
  {
    id: `${prefix}_floor`,
    face: 'floor',
    position: 0.5,
    type: 'open',
    systems: ['structural', 'electrical-low-voltage'],
    required: false,
  },
  {
    id: `${prefix}_ceiling`,
    face: 'ceiling',
    position: 0.5,
    type: 'open',
    systems: ['hvac-supply', 'hvac-return', 'electrical-120v'],
    required: false,
  },
];

export const bedroom_primary: RoomModule = {
  id: 'bedroom_primary',
  name: 'Primary Bedroom',
  category: 'bedroom',
  variant: 'primary',
  dimensions: { width: 4.5, depth: 5.0, height: 2.7 },
  gridSize: { x: 9, y: 10 },
  connectors: baseConnectors('br_primary'),
  systemsNodes: [
    {
      id: 'br_primary_hvac_reg',
      type: 'hvac-register',
      localPosition: { x: 0.5, y: 0.95, z: 0.2 },
      channels: ['hvac-supply'],
      label: 'Supply Register',
      cfm: 120,
    },
    {
      id: 'br_primary_return',
      type: 'hvac-return-grille',
      localPosition: { x: 0.5, y: 0.95, z: 0.8 },
      channels: ['hvac-return'],
      label: 'Return Grille',
      cfm: 100,
    },
    {
      id: 'br_primary_outlet_n',
      type: 'electrical-outlet',
      localPosition: { x: 0.2, y: 0.15, z: 0.05 },
      channels: ['electrical-120v'],
      label: 'Outlet NE',
      watts: 0,
    },
    {
      id: 'br_primary_outlet_s',
      type: 'electrical-outlet',
      localPosition: { x: 0.8, y: 0.15, z: 0.95 },
      channels: ['electrical-120v'],
      label: 'Outlet SW',
      watts: 0,
    },
    {
      id: 'br_primary_light',
      type: 'electrical-fixture',
      localPosition: { x: 0.5, y: 1.0, z: 0.5 },
      channels: ['electrical-120v'],
      label: 'Ceiling Light',
      watts: 60,
    },
  ],
  planColor: '#c8d8e8',
  icon: 'bed-double',
  minCount: 1,
  repeatable: true,
  notes: 'Primary bedroom. Minimum 4.5x5m. Requires direct hallway or ensuite access.',
};

export const bedroom_guest: RoomModule = {
  id: 'bedroom_guest',
  name: 'Guest Bedroom',
  category: 'bedroom',
  variant: 'guest',
  dimensions: { width: 3.5, depth: 4.0, height: 2.7 },
  gridSize: { x: 7, y: 8 },
  connectors: baseConnectors('br_guest'),
  systemsNodes: [
    {
      id: 'br_guest_hvac_reg',
      type: 'hvac-register',
      localPosition: { x: 0.5, y: 0.95, z: 0.15 },
      channels: ['hvac-supply'],
      label: 'Supply Register',
      cfm: 80,
    },
    {
      id: 'br_guest_light',
      type: 'electrical-fixture',
      localPosition: { x: 0.5, y: 1.0, z: 0.5 },
      channels: ['electrical-120v'],
      label: 'Ceiling Light',
      watts: 60,
    },
    {
      id: 'br_guest_outlet',
      type: 'electrical-outlet',
      localPosition: { x: 0.2, y: 0.15, z: 0.05 },
      channels: ['electrical-120v'],
      label: 'Outlet',
      watts: 0,
    },
  ],
  planColor: '#d8e8c8',
  icon: 'bed-single',
  minCount: 0,
  repeatable: true,
  notes: 'Guest bedroom. Minimum 3.5x4m.',
};